### ISSUE TITLE
How to create default page when removed

### ISSUE THREAD

**Issue by sanicode** [luyadev/luya#1782] opened 2018-03-26 06:36 UTC
Not Found (#404)
Home item could not be found, have you forget to set a default page?
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

2018-03-26 07:53:07

**Comment by nadar** [comment] 2018-03-26 06:42
hi @sanicode so you have to make sure your homepage is "online" (but can be hidden) and also your language in the config matches the default language in admin "language" table.

**Comment by sanicode** [comment] 2018-03-26 10:24
Hi @nadar thanks for comment, i found the same result for your advice. This error occured when deleting default homepage.

**Comment by nadar** [comment] 2018-03-26 10:35
So its not a bug and we can close the issue?

**Comment by sanicode** [comment] 2018-03-26 10:47
My question is how to add default homepage again, thanks

**Comment by nadar** [comment] 2018-03-26 10:48
Just click on the settings button of a page and visit the "default page" link:

![image](https://user-images.githubusercontent.com/3417221/37902209-f7d68174-30f3-11e8-8787-56eff22f9d45.png)

**Comment by sanicode** [comment] 2018-03-26 10:52
It's a bug because, that feature doesn't work, my default homepage still error 404

**Comment by nadar** [comment] 2018-03-26 10:53
And this page (which is the default page) is not offline? 

![image](https://user-images.githubusercontent.com/3417221/37902399-9d2744ce-30f4-11e8-8d1d-b13c9ab5de8e.png)

**Comment by sanicode** [comment] 2018-03-26 11:26
Everything looks fine, but still error 404. can you try it, for example delete your current homepage, and then recreated it again. If succeed may be something gone be wrong with mine

**Comment by nadar** [comment] 2018-03-26 11:50
1. Delete my current DEFAULT-PAGE
2. Reload frontend = 404 exception
3. Create a new page.
4. Swtich new page to "online" and "visible".
5. Set new page as DEFAULT-PAGE
6. Works fine. Content of new homepage is displayed.

**Comment by sanicode** [comment] 2018-03-26 12:09
thanks @nadar i'll try it. How to find the complete docs like that?

**Comment by nadar** [comment] 2018-03-26 12:19
Well, we have a lot of documentation here: https://luya.io/guide - but this guide is more focused on developers. Your request is more an "end user" documentation thing, which is currently missing. We try to make the UI as self-explaining as possible. 

Maybe we should just deactivated the deleted button when a page is the homepage. What do you think?

**Comment by sanicode** [comment] 2018-03-26 12:35
No no no. I don't think so, this feature is a good deal for CMS. Because maybe someone need to change the default homepage with their own. As a developer, i still confuse about UI&UX luya admincms page.

**Comment by nadar** [comment] 2018-03-26 12:37
They can still change the homepage on their own, but if a page is the default page, it can not be deleted unless you make another page your default page.

Can you give us a concrete example of what confuses you? So maybe we can improve this.

**Comment by sanicode** [comment] 2018-03-26 12:42
![image](https://user-images.githubusercontent.com/6724789/37906748-49296c74-312d-11e8-867d-beee3d16862b.png)
as example this menu, first I don't realize that menu is part of feature of the Pages. Usually, some designer use Gear icon, and located near the pages layout design

**Comment by nadar** [comment] 2018-03-26 12:48
@luyadev/coredev what about using gear icons?

**Comment by TheMaaarc** [comment] 2018-03-26 13:15
Sounds good to me.
Maybe we should think about merging the two menus (edit button on the right of the page title) and the `three dot menu`. I can't really see a reason why we still have that separation, it's mostly just confusing and in 1 out of 2 cases I search in the wrong place.


![untitled-1](https://user-images.githubusercontent.com/3450438/37908319-30790268-3108-11e8-8ed4-be7c3c684738.jpg)

**Comment by nadar** [comment] 2018-03-26 13:20
@TheMaaarc The reason for having two edit icons is indeed a bit confusing, but the *tree dot menu* is editing the NAV while the edit icon changes the data inside the NAV_ITEM table **for each language.**

**Comment by sanicode** [comment] 2018-03-26 13:40
may i provide design idea for a better UI & UX @nadar ?i'm interesting to develop luya too

**Comment by nadar** [comment] 2018-03-26 13:45
Sure, everyone can join, provide ideas and make pull requests. We made a complete overhaul of the admin 9 months ago, so providing small ideas for improvements have bigger change of being accepted, maybe keep this in mind :-)

**Comment by dev7ch** [comment] 2018-03-26 13:54
@luyadev/coredev gear icon would be better as the three dots IMO ( would probably be the same icons as in mainnav for settings)

**Comment by nadar** [comment] 2018-03-26 15:48
@dev7ch 

> The reason for having two edit icons is indeed a bit confusing, but the three dot menu is editing the NAV while the edit icon changes the data inside the NAV_ITEM table for each language.

**Closed** 2018-03-26 15:49 UTC
Labels: discussion, pkg:cms
