### ISSUE TITLE
zaa-checkbox in block

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#835] opened 2016-04-18 14:08 UTC
Used a zaa-checkbox in cfg of block. It didn't got serialized and sent to the server (cfg json not in db).

```
'cfgs' => [
    ['var' => 'groupCaptions', 'label' => 'Mobil: Legenden Gruppieren', 'type' => 'zaa-checkbox'],
]
```

**Comment by nadar** [comment] 2016-08-04 13:39
Can't reproduce. I guess this has been fixed by solving another problem (empty array save of in database).

**Closed** 2016-08-04 13:42 UTC
Labels: bug, bug_can't_reproduce
