### ISSUE TITLE
Problem with installing luya

### ISSUE THREAD

**Issue by Archangel199512** [luyadev/luya#1142] opened 2017-01-09 14:09 UTC
Hello! When I'm trying to import database by executing 'composer exec luya import' I'm getting an error: Exception while importing: 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luya.admin_property' doesn't exist I need help)))

**Comment by nadar** [comment] 2017-01-09 14:10
Hi @Archangel199512 

Run the following commands in this order and post the response:

```sh
composer exec luya migrate
composer exec luya import
```

**Comment by Archangel199512** [comment] 2017-01-09 14:12
Yes, when I'm trying to execute the second line I'm getting this error.

**Comment by nadar** [comment] 2017-01-09 14:13
Yes but what is the response of the first command?

**Comment by nadar** [comment] 2017-01-09 14:16
and what if you then enter "y" (yes) and press enter?

**Comment by Archangel199512** [comment] 2017-01-09 14:18
I can't because it immediately throws me to another input line and I can't presse yes and enter.

**Comment by nadar** [comment] 2017-01-09 14:22
Hmm, that sounds intresting and is maybe related to the `composer exec` command. As i am not used to windows i can not reproduce. But there are also other windows user's running this command successfull.

Could you post me a screenshot of this behavior: 

> I can't because it immediately throws me to another input line

**Comment by nadar** [comment] 2017-01-09 14:32
You could use  --interactive=0 but you will have to enter also values for the setup command. 

```sh
composer exec luya migrate --interactive=0
```

When the `Apply the above migrations? (yes|no) [no]:` prompt dialog is shown, just type `y` and press `Enter` will abort the command?

**Comment by Archangel199512** [comment] 2017-01-09 14:36
No, it just prints:
The "--interactive" option does not exist.

**Comment by nadar** [comment] 2017-01-09 14:38
works fine on my mac

```php
./vendor/bin/luya migrate --interactive=0
Yii Migration Tool (based on Yii v2.0.10)

No new migrations found. Your system is up-to-date.
```

**Comment by nadar** [comment] 2017-01-09 14:39
could you maybe show me your composer.json file?

**Comment by Archangel199512** [comment] 2017-01-09 14:40
[composer.txt](https://github.com/luyadev/luya/files/693714/composer.txt)

**Comment by nadar** [comment] 2017-01-09 14:43
Hmm this is really wired! This is maybe not even related to LUYA when you are not able to input data from console as we are using the yii console confirm method (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseConsole.php#L822)

are you able to access the php.exe file?

cause then you could also run the commands from the public_html folder:

```sh
php.exe index.php migrate
```

(inside the `/public_html` folder then)

**Comment by Archangel199512** [comment] 2017-01-09 14:52
Yeah, it works. Thank you very much))

**Comment by nadar** [comment] 2017-01-11 10:48
I can confirm the problem with `composer exec` on windows.

Related:
https://github.com/composer/composer/pull/4036
https://github.com/composer/composer/issues/5615

**Comment by nadar** [comment] 2017-01-11 10:51
![composer exec](https://cloud.githubusercontent.com/assets/3417221/21845787/511aad82-d7f4-11e6-989f-9fa08b00187c.png)

**Comment by nadar** [comment] 2017-02-02 11:56
I have revert the documentations guide to notify other people to use the `php index.php` script in order to run commands, but i keep the issue open in order to see if something changes in the related composer issues: https://github.com/luyadev/luya/issues/1142#issuecomment-271837587

**Comment by nadar** [comment] 2017-05-02 09:38
@Archangel199512 I am going to close this issue as the documentation on luya.io is up-to-date since rc3 release. But sure i will keep an eye on the composer issues so hopefully in future we can handle such commands via composer as well. Thanks for the report.

**Closed by nadar** 2017-05-02 09:38 UTC
Labels: enhancement:docs, question & support
