### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by EyrikhVI** [luyadev/luya#1920] opened 2019-05-06 16:28 UTC
### What steps will reproduce the problem?
$ php index.php import

luya\cms\admin\importers\BlockImporter:
╔═════╤═════════════════════════════════════════════════════════════════════════════════════════╗
║ Key │ Value                                                                                   ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 0   │ Insert new block group block_group_dev_elements.                                        ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 1   │ block \luya\cms\frontend\blocks\HtmlBlock: Added to database                            ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 2   │ block \luya\cms\frontend\blocks\ModuleBlock: Added to database                          ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 3   │ Unable to process block definition 'vendor\luyadev/luya-bootstrap3\src/blocks'          ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 4   │ Unable to process block definition 'vendor\luyadev/luya-generic\src/blocks'             ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 5   │ Unable to process block definition 'vendor\luyadev/luya-module-cms\src/frontend/blocks' ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 6   │ Block importer finished with 2 blocks.                                                  ║
╚═════╧═════════════════════════════════════════════════════════════════════════════════════════╝

### What is the expected result?

![image](https://user-images.githubusercontent.com/41295996/57238370-93cd6080-706c-11e9-8f38-80c84c29df5c.png)

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/41295996/57238191-26213480-706c-11e9-9121-c7af994f49f3.png)

I have no development blocks, except two

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '22519'
4: [phpversion()] '7.2.0'
5: [php_ini_loaded_file()] 'C:\\OSPanel\\modules\\php\\PHP-7.2\\php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | LUYA import command (based on LUYA 1.0.17)
| PHP Version      |7.2
| Platform         | OpenServer
| Operating system | Windows/

**Comment by nadar** [comment] 2019-05-06 18:41
@EyrikhVI Thanks for this report, i assume this is the problem of wrong paths provided in luya composer => https://github.com/luyadev/luya-composer/issues/10

Could you please provide me the **installer.php** file from **vendor/luyadev** folder?

**Comment by EyrikhVI** [comment] 2019-05-06 21:03
[installer.txt](https://github.com/luyadev/luya/files/3149835/installer.txt)

**Comment by nadar** [comment] 2019-05-07 07:12
I close this issue here, as the problem is reported in luya composer repo, please add more infos there. thank you very much for the report.

**Closed by nadar** 2019-05-07 07:12 UTC
Labels: bug:research
