### ISSUE TITLE
loading empty css file

### ISSUE THREAD

**Issue by pironmind** [luyadev/luya#1968] opened 2019-10-22 20:53 UTC
### What steps will reproduce the problem?

maybe after composer install, but undefined why this stop to work.
Data was not modified and written by yours documentation.
Not loaded only ```css/fontello/css/fontello.css```

### What is the expected result?

loaded data

```php
class LandingAsset extends \luya\web\Asset
{
    public $sourcePath = '@app/resources';
    public $css = [
        'css/hamburgers.min.css?v=1513163921',
        'css/bootstrap.min.css?v=1513163921',
        'css/owl.carousel.min.css?v=1513163921',
        'css/owl.theme.default.min.css?v=1513163921',
        'css/main.min.css?v=1513163921',
        'css/animate.min.css?v=1513163921',
        'css/form.css?v=1513163921',
        'css/fontello/css/fontello.css',
    ];
```
```php 
// view/layouts

use app\assets\LandingAsset;
use luya\helpers\Html;
use luya\web\View;

/* @var $this luya\web\View */
/* @var $content string */

LandingAsset::register($this);
```

### What do you get instead? (A Screenshot can help us a lot!)

Any idea why this happened?

![image](https://user-images.githubusercontent.com/34869675/67331535-8e82a600-f526-11e9-9c30-39c09a8603e6.png)

![image](https://user-images.githubusercontent.com/34869675/67331652-b2de8280-f526-11e9-80d9-76b7af304753.png)

![image](https://user-images.githubusercontent.com/34869675/67329925-38146800-f524-11e9-8a2e-1fc4897729b1.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.10.0
| PHP Version      | 7.2.0
| Platform         | Apache/Openserver (https://ospanel.io)
| Operating system | Windows10-stable

**Comment by pironmind** [comment] 2019-10-22 21:16
And how the system select assets id, on diffrent servers I have new one?

**Comment by nadar** [comment] 2019-10-23 06:54
hi @pironmind 

1. `?v=1513163921` is not needed in the asset file, yii will do this automatically. Remove it, maybe it makes the trouble.
2. Please take a look at Yii Guide for general questions about Assets: https://www.yiiframework.com/doc/guide/2.0/en/structure-assets
3. So the problem is that the assets are published, but empty?

**Comment by pironmind** [comment] 2019-10-23 22:58
That asset is empty. I directly copy to the loaded id folder and this work (understand that this is crutch).

**Comment by nadar** [comment] 2019-10-24 06:32
did you followed my advice to remove the version param in the assest file?

**Comment by pironmind** [comment] 2019-10-25 00:49
> did you followed my advice to remove the version param in the assest file?

remove, but did not help

**Comment by nadar** [comment] 2019-10-26 07:49
I really would like to help you on this. 

1. have you setup that the asset manager should use symlinking instead of copy? cause you are working in windows, this might not work.

2. have seen this folder, it looks like the foldername contains the slash, or is it your IDE?

<img width="204" alt="Bildschirmfoto 2019-10-26 um 09 48 11" src="https://user-images.githubusercontent.com/3417221/67616177-f4488980-f7d5-11e9-995c-8eefa00558b9.png">

**Comment by pironmind** [comment] 2019-10-26 20:29
> I really would like to help you on this.
> 
> 1. have you setup that the asset manager should use symlinking instead of copy? cause you are working in windows, this might not work.
> 2. have seen this folder, it looks like the foldername contains the slash, or is it your IDE?
> 
> <img alt="Bildschirmfoto 2019-10-26 um 09 48 11" width="204" src="https://user-images.githubusercontent.com/3417221/67616177-f4488980-f7d5-11e9-995c-8eefa00558b9.png">

1) sourcePath is set
`
class LandingAsset extends \luya\web\Asset {
     public $sourcePath = '@app/resources';
`
2) it is folder inside the another one folder ` / -> resources -> css -> fontello -> css -> <main file>`. Or `'css/fontello/css/fontello.css'`. (just google chrome debugger)

**Comment by nadar** [comment] 2019-10-27 14:00
1. make sure `linkAssets` is disabled in the config.
2. try to remove all folders `public_html/assets`.

**Comment by nadar** [comment] 2019-12-09 18:45
If there is something i can help, please let me know. otherwise i will close the issue as there is no further activity since 27.10

**Closed by nadar** 2019-12-09 18:45 UTC
Labels: bug:research, help wanted
