### ISSUE TITLE
Bug with language

### ISSUE THREAD

**Issue by ASYOU99** [luyadev/luya#1162] opened 2017-01-16 13:44 UTC
1. Please add to site in part install information from https://github.com/luyadev/luya/issues/1142 because I have this problem to.
2. When I "composer exec luya setup" and then select other language example Russian and short code ru in ma brauser I have 404 problem. Whem I change in Db language to English all is ok. Maybe add in the menu list of the languages which can be selected and codes that have been mozhneo select the language from the very beginning of the installation.
3. I do not see Ukrainian language after install.

**Comment by nadar** [comment] 2017-01-16 13:56
1. Yes i already changed the guide, so people have to use `php.exe` / `php` instead of composer exec. => https://github.com/luyadev/luya/commit/d4d8040ae4263e6624d6004494170b56c0944a65#diff-a766d7b80897afd829051763d325d9b1 But we can not push it to the site (luya.io) yet, as also other things have changed during the 1.0.0 development. :disappointed: 

2. Do you mean a list of languages during the setup process?

**Comment by ASYOU99** [comment] 2017-01-16 14:00
yes for example i wrire Russian and ru then I have 404

**Comment by nadar** [comment] 2017-01-16 14:02
This is because the composition language (https://github.com/luyadev/luya-kickstarter/blob/master/configs/env-local.php#L107) has to match your default language (the language u enter during the setup process).

**Comment by ASYOU99** [comment] 2017-01-16 14:05
Perhaps then it is better to remove the parameter memory when installing because if someone enters something that does not receive an error and nesmozhet understand. "Never untrusted users" - the first rule programmista.I I just confirmed it :)

**Comment by nadar** [comment] 2017-01-16 14:07
Maybe i can change the value of the config afterwards, or i going to build a easy wizzard which builds the config for you, checks database, and run the migrate, import and setup commands.

**Comment by ASYOU99** [comment] 2017-01-16 14:11
And when I add a new language in the system there is no delete function only add.

**Comment by nadar** [comment] 2017-01-16 14:18
its done and will be part of 1.0.0 release: https://github.com/luyadev/luya/issues/1010

**Comment by ASYOU99** [comment] 2017-01-16 14:26
If I create a new page without selecting a template, and then make it home I can`t add to it any content and attempt to access it causes an error "Could not find the requested cms layout id '0' for nav item page id '4'. Make sure your page does not have an old inactive / deleted cms layout selected. " I understand that I am still learning to work with the "yula" but may have to do so foolproof.

**Comment by ASYOU99** [comment] 2017-01-16 14:33
When I'm in the system added a new language made it the default and then returned back to English in editing pages in menyach still displays the old language is not returned to the default.

**Comment by nadar** [comment] 2017-01-16 14:35
> and then make it home I can`t add to it any content and attempt to access it causes an error

I am not able to reproduce this problem?

**Comment by ASYOU99** [comment] 2017-01-16 14:43
![image](https://cloud.githubusercontent.com/assets/12735688/21987105/c8de16f0-dc0a-11e6-8e4e-174283e3ad70.png)
With these parameters, the template is created, and if you click in the template field to edit it I nesmog nothing to do with it (it nedobavlyayutsya gtkakie elements that would make the new template)

**Comment by nadar** [comment] 2017-01-16 14:49
True! It should return a warning that template can not be empty. thanks!

**Comment by ASYOU99** [comment] 2017-01-16 14:56
Also I did not find where to change the system messages language in admin panel (language selection panel is). If the "env-local" change the language only then change the message. Also, even if yayzk Change messages to Russian here is why it is still not visible.
![image](https://cloud.githubusercontent.com/assets/12735688/21987559/bcdd66ce-dc0c-11e6-8bfc-03072b6e3b4d.png)

**Comment by nadar** [comment] 2017-01-16 14:59
Whats written in `https://github.com/luyadev/luya-kickstarter/blob/master/configs/env-local.php#L107` ?

**Comment by nadar** [comment] 2017-01-16 15:03
True! The user language overrides the yii language in the admin interface on order to display correct model validations.

**Comment by ASYOU99** [comment] 2017-01-16 15:04
ru. I have edited this post because after installation I did not find how to change the language of the system sooscheny differently. Also, if the parent page is created then move it where the subsidiary can only dragging (in the Edit Settings page does not select for her parents)

**Comment by ASYOU99** [comment] 2017-01-16 15:07
I am a bit do not understand your last message. (How to change the user language of system messages without touching the code)

**Comment by nadar** [comment] 2017-01-16 15:11
![selection_025](https://cloud.githubusercontent.com/assets/3417221/21988116/5dedf594-dc06-11e6-99a6-9503bc2fbf1a.png)

**Comment by ASYOU99** [comment] 2017-01-16 15:12
Yes, I'm doing but why that system messages I do not change

**Comment by ASYOU99** [comment] 2017-01-16 15:12
![image](https://cloud.githubusercontent.com/assets/12735688/21988171/02e48696-dc0f-11e6-82de-4a6f7c28efd5.png)

**Comment by ASYOU99** [comment] 2017-01-16 15:14
in  (https://github.com/luyadev/luya-kickstarter/blob/master/configs/env-local.php#L107) "ru"

**Comment by nadar** [comment] 2017-01-16 15:21
Not sure what's going wrong there - I need more informations but maybe you should drop all tables again and run migrate, import and setup, on setup you enter "Russian" and "ru" like in your composition config. In order to have the admin interface in russia you can configure "luyaLanguage" to ru. Maybe you should also install the dev-master as we have fixed a lot of things until rc2, or you wait until 1.0.0 will be release (end of the month).

Thanks for the two bug reports with the empty template and the luyaLanguage problem in the "debug bar".

**Comment by ASYOU99** [comment] 2017-01-16 15:24
Ok language for me not critikal bug. I wait release and test my error.

**Comment by ASYOU99** [comment] 2017-01-16 15:28
![image](https://cloud.githubusercontent.com/assets/12735688/21988756/10f8d226-dc11-11e6-8508-21e745344088.png)
Miracles :) Russian Language, the code is Russian and some errors are displayed in German :) (I guess that is where it is not reset when I change the language via admin panel)

**Comment by ASYOU99** [comment] 2017-01-16 15:28
I'll wait for the release.

**Comment by nadar** [comment] 2017-01-16 17:02
@ASYOU99 the language problem is already solved.

**Closed** 2017-01-17 14:56 UTC
Labels: bug, question & support
