### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bahrammzm** [luyadev/luya#1468] opened 2017-09-09 07:17 UTC
![issue](https://user-images.githubusercontent.com/15061349/30238045-356d5a30-9554-11e7-9a4d-522abedbe299.JPG)

**Comment by dev7ch** [comment] 2017-09-09 07:20
Did you run `composer install` inside of 'luya/envs/dev/' ?

**Comment by bahrammzm** [comment] 2017-09-09 07:21
Yes , i did

**Comment by nadar** [comment] 2017-09-09 07:24
could you please provide me the steps to reproduce, i assume something like this:

+ clone luyadev/luya repo
+ copy env config in /envs/dev/configs
+ run composer install
+ cd public_html
+ php index.php migrate -> exception.

An it seems to be windows?

**Comment by bahrammzm** [comment] 2017-09-09 07:33
I did all steps according to guide . Yes it's windows

**Comment by nadar** [comment] 2017-09-09 07:57
ok, but you are trying to install the luya dev environment not the kickstarter, is that excepted?

**Comment by bahrammzm** [comment] 2017-09-09 08:14
Do you suppose this issue is because of windows platform ?!

**Comment by nadar** [comment] 2017-09-09 09:07
Not sure yet, the dev env works on my system. It seems that the @vendor alias can not be found. I am going to test. Thanks for the report.

**Comment by nadar** [comment] 2017-09-09 10:31
I found the bug, its because the directory seperator handles the input as given sub alias.

I am going to fix that

`````php
$vendor = Yii::getAlias('@vendor');
$file = $vendor . DIRECTORY_SEPARATOR . 'luyadev' . DIRECTORY_SEPARATOR . 'installer.php';
````

in

getPackageInstaller of application trait.

**Comment by nadar** [comment] 2017-09-09 11:04
@bahrammzm i just pushed a fix. Could you please update your fork, pull the fix and try again? thank you

**Closed** 2017-09-14 07:27 UTC
Labels: bug
