### ISSUE TITLE
Wrong sorting of numbers in CRUD list view

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1042] opened 2016-10-21 07:59 UTC
### What steps will reproduce the problem?

Sort a column with numbers in CRUD list view.
### What is the expected result?

Numeric sorting.
### What do you get instead? (A Screenshot can help us a lot!)

Alphabetical sorting:

![sorting of numbers](https://cloud.githubusercontent.com/assets/3786245/19590986/04efbfac-9775-11e6-8d0f-a538138b06f6.png)

**Comment by nadar** [comment] 2016-10-21 08:09
Please show me the ngrest config for this field.

**Comment by nadar** [comment] 2016-11-06 20:46
@rolandschaub still waiting for informations.

**Comment by nadar** [comment] 2017-05-02 09:08
@rolandschaub Unable to reproduce, i am going to close this issue. If you have any further problems, please create a new issue.

**Closed by nadar** 2017-05-02 09:08 UTC
Labels: bug:research, waiting_for_informations
